name = "chhsban-acadoc-api"
type = "javascript"
account_id = ""
workers_dev = true

[env.production]
route = "api.example.com/api/*"
zone_id = ""

[[kv_namespaces]]
binding = "CACHE"
id = ""
preview_id = ""

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts"]

[build.upload]
format = "modules"
main = "./dist/worker.js"
